# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: wsl2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download installer tarball
        uses: carlosperate/download-file-action@v1.1.1
        with:
          file-url: https://s3.eu-central-1.wasabisys.com/nzbr/nixos-wsl-installer.tar.gz
          file-name: installer.tar.gz
          
      - run: whoami
          
      - name: Import WSL Distro
        run: wsl --import "${{github.sha}}" .\"${{github.sha}}" installer.tar.gz --version 2
        
      - name: Boot the distro
        run: wsl -d "${{github.sha}}" systemctl status
          
      - name: Terminate the distro
        if: always()
        run: wsl -t "${{github.sha}}"
          
      - name: Cleanup
        if: always()
        run: wsl --unregister "${{github.sha}}"
        
