# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v16
        
      - name: Build tarball
        run: nix build 'github:nzbr/NixOS-WSL#nixosConfigurations.mysystem.config.system.build.tarball'
        
      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: rootfs
          path: result/tarball/nixos-wsl-x86_64-linux.tar.gz
      
      - name: Build installer
        run: nix build 'github:nzbr/NixOS-WSL#nixosConfigurations.mysystem.config.system.build.installer'
        
      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: result/tarball/nixos-wsl-installer.tar.gz        

  test:
    runs-on: wsl2
    
    needs:
      - build
      
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download installer tarball
        uses: actions/download-artifact@v2
        with:
          name: installer
          
      - name: Import WSL Distro
        run: wsl --import "${{github.sha}}" .\"${{github.sha}}" result\tarball\nixos-wsl-installer.tar.gz --version 2
        
      - name: Boot the distro
        run: wsl -d "${{github.sha}}" systemctl status
          
      - name: Terminate the distro
        if: always()
        run: wsl -t "${{github.sha}}"
          
      - name: Cleanup
        if: always()
        run: wsl --unregister "${{github.sha}}"
        
